myblog-0.1.1/backend/urls.py
from django.urls import path, re_path
from .views import backend
from .views import article
from .views import category
from .views import tag


app_name = 'app-backend'
urlpatterns = [
    path('article.html', article.article, name="backend-article"),
    path('article-pic', article.article_pic, name='backend-article-pic'),
    path('category.html', category.category, name='backend-category'),
    path('tag.html', tag.tag, name="backend-tag"),
    path('logout.html', backend.logout, name="backend-logout"),
    path('', backend.index, name='backend-index'),
    re_path('set', backend.develop, name='backend-set'),            # 待开发
    re_path('(interest)|(updown).html', backend.develop, name='backend-interest'),
]

myblog-0.1.1/myBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('backend/', include('backend.urls')),
    path('', include('web.urls')),
]

myblog-0.1.1/web/urls.py
from django.urls import path, re_path
from .views import account, home


app_name = 'user-web'
urlpatterns = [
    path('reg.html', account.ajax_reg, name='reg'),
    path('login.html', account.ajax_login, name='login'),
    path('logout.html', account.ajax_logout, name='logout'),
    path('check_code', account.check_code, name="check_code"),
    path('<str:site>.html', home.article_list, name="home_article_list"),
    re_path(r'^(?P<site>\w+)/(?P<condition>((tag)|(category)|(date)))/(?P<val>\w+(-\w+)*).html$',
            home.article_query, name="home_article_query"),
    path('<str:site>/<int:nid>.html', home.article_detail, name="home_article_detail"),
    path('', home.index, name='index'),
]

myblog-0.1.1/web/models.py
from django.db import models

# Create your models here.


class WebPlate(models.Model):
    """
    网站首页分为多少个板块
    """
    class Meta:
        db_table = "webplate"
    nid = models.AutoField(primary_key=True, auto_created=True)
    title = models.CharField(max_length=48)


class User(models.Model):
    class Meta:
        db_table = "user"
    nid = models.AutoField(primary_key=True, auto_created=True)
    name = models.CharField(max_length=48, null=False, default=None, unique=True, verbose_name="用户登录名")
    email = models.EmailField(verbose_name="邮箱", unique=True)
    pwd = models.CharField(max_length=128, verbose_name="密码")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    nickname = models.CharField(max_length=48, verbose_name="昵称", null=True)
    avatar = models.ImageField(upload_to="static/img/avatar/", null=True, verbose_name="头像")

    # 正向查找通过fans来查询用户有多少粉丝，
    # 多对多必须定义related_name以反向查找管理器对象名，用于查找用户关注的人
    fans = models.ManyToManyField(to="User",
                                  through="UserFans",
                                  through_fields=('user', 'follower'),
                                  verbose_name='粉丝们',
                                  related_name="interests")

    def __str__(self):
        return self.name


class Blog(models.Model):
    class Meta:
        db_table = "blog"
    nid = models.AutoField(primary_key=True, auto_created=True)
    user = models.OneToOneField(to="User", to_field="nid", null=True, on_delete=models.SET_NULL)
    site = models.CharField(max_length=32, unique=True, verbose_name="个人博客主页名")
    title = models.CharField(max_length=64, verbose_name="个人博客标题")
    theme = models.CharField(max_length=32, default="warm.css", verbose_name="个人博客主题")
    memo = models.CharField(max_length=255, null=True, default=None, verbose_name="座右铭")

    def __str__(self):
        return self.site


class UserFans(models.Model):
    class Meta:
        db_table = "userfans"
        unique_together = [("user", "follower")]
    nid = models.AutoField(primary_key=True, auto_created=True)
    user = models.ForeignKey(to="User", to_field="nid", related_name="users",
                             null=True, on_delete=models.SET_NULL, verbose_name="博主")
    follower = models.ForeignKey(to="User", to_field='nid', related_name="followers",
                                 null=True, on_delete=models.SET_NULL, verbose_name="粉丝")

    def __str__(self):
        return "{}<-{}".format(self.user.name, self.follower.name)


class Tag(models.Model):
    class Meta:
        db_table = "tag"
    nid = models.AutoField(primary_key=True, auto_created=True)
    title = models.CharField(max_length=32, verbose_name="文章标签")
    blog = models.ForeignKey(to="Blog", to_field="nid", null=True, on_delete=models.SET_NULL, verbose_name="所属博客")
    is_delete = models.BooleanField(verbose_name="逻辑删除", default=False)

    def delete(self, using=None, keep_parents=False):
        self.is_delete = True
        self.save()
        for a2t in self.articlem2mtag_set.all():
            a2t.delete()

    def __str__(self):
        return self.title


class Category(models.Model):
    class Meta:
        db_table = "category"
    nid = models.AutoField(primary_key=True, auto_created=True)
    title = models.CharField(max_length=32, verbose_name="文章分类")
    blog = models.ForeignKey(to="Blog", to_field="nid", null=True, on_delete=models.SET_NULL, verbose_name="所属博客")
    is_delete = models.BooleanField(verbose_name='逻辑删除', default=False)

    def delete(self, using=None, keep_parents=False):
        self.is_delete = True
        self.save()
        for a in self.article_set.all():    # TODO 是否有必要将一对多的一段置为null，可以在Article查询时添加category__is_delete
            a.category_id = None
            a.save()

    def __str__(self):
        return self.title


class Article(models.Model):
    class Meta:
        db_table = "article"
    nid = models.AutoField(primary_key=True, auto_created=True)
    blog = models.ForeignKey(to="Blog", to_field='nid', null=True, on_delete=models.SET_NULL, verbose_name="所属博客")
    title = models.CharField(max_length=128, verbose_name="文章标题")
    summary = models.CharField(max_length=255, verbose_name="文章概要")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    read_count = models.IntegerField(default=0, verbose_name="阅读次数")
    comment_count = models.IntegerField(default=0, verbose_name="评论次数")
    up_count = models.IntegerField(default=0, verbose_name="赞次数")
    down_count = models.IntegerField(default=0, verbose_name="踩次数")
    tag = models.ManyToManyField(to="Tag", through="ArticleM2MTag", through_fields=["article", "tag"])
    category = models.ForeignKey(to="Category", to_field="nid", null=True, on_delete=models.SET_NULL, verbose_name="分类")
    webplate = models.ForeignKey(to='WebPlate', to_field='nid', null=True, on_delete=models.SET_NULL,
                                 verbose_name="所属网站分类")
    is_delete = models.BooleanField(verbose_name='逻辑删除', default=False)

    def delete(self, using=None, keep_parents=False):
        self.is_delete = True
        self.save()
        self.articledetail.delete()                 # 将文章内容逻辑删除
        for a2t in self.articlem2mtag_set.all():    # 将文章标签逻辑删除
            a2t.delete()

    def __str__(self):
        return self.title


class ArticleDetail(models.Model):
    class Meta:
        db_table = "articlecontent"
    nid = models.AutoField(primary_key=True, auto_created=True)
    content = models.TextField(verbose_name="文章内容")
    article = models.OneToOneField(to="Article", to_field="nid", null=True, on_delete=models.SET_NULL,
                                   verbose_name="所属文章")
    is_delete = models.BooleanField(verbose_name="删除标记", default=False)

    def delete(self, using=None, keep_parents=False):
        self.is_delete = True
        self.save()

    def __str__(self):
        return '{}-{}的正文'.format(self.nid, self.article.title)


class ArticleM2MTag(models.Model):
    class Meta:
        db_table = "articlem2mtag"
        unique_together = (("article", "tag"),)
    nid = models.AutoField(primary_key=True, auto_created=True)
    article = models.ForeignKey(to="Article", to_field="nid", null=True, on_delete=models.SET_NULL, verbose_name="文章")
    tag = models.ForeignKey(to="Tag", to_field="nid", null=True, on_delete=models.SET_NULL, verbose_name="标签")
    is_delete = models.BooleanField(verbose_name="删除标记", default=False)

    def delete(self, using=None, keep_parents=False):
        self.is_delete = True
        self.save()

    def __str__(self):
        return "{}-{}".format(self.article.title, self.tag.title if self.tag else None)

myblog-0.1.1/templates/backend_article.html
{% extends 'backend_layout.html' %}

{% block css %}
    {% load static %}
    <script src="{% static 'js/ajaxAction.js' %}"></script>
    <script>
    $(function(){
        ajaxDeleteEvent('.option-delete');
    })
    </script>
{% endblock %}

{% block content %}
    <div class="article-list-area">
        <div class="article-option">
            {% if 'add' in request.user_action %}
                <a class="btn btn-success" href="{{ request.path_info }}?t=add">新随笔</a>
            {% endif %}
        </div>
        <table class="article-table table table-hover">
            <thead>
            <tr>
                <th class="article-title">标题</th>
                <th class="article-pubtime">发布时间</th>
                <th class="article-category">所属分类</th>
                <th>阅读数</th>
                <th>评论数</th>
                <th class="article-ope">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for article in article_lst %}
                <tr aid="{{ article.nid }}">
                    <td><a href="/{{ request.logged_blog.site }}/{{ article.nid }}.html">{{ article.title }}</a></td>
                    <td>{{ article.create_time|date:"Y-m-d" }}</td>
                    <td>{{ article.category.title }}</td>
                    <td>{{ article.read_count }}</td>
                    <td>{{ article.comment_count }}</td>
                    <td>
                        {% if 'edit' in request.user_action %}
                            <a href="{{ request.path_info }}?t=edit&aid={{ article.nid }}">编辑</a>
                        {% endif %}
                        {% if 'delete' in request.user_action %}
                            <a class="option-delete" href="{{ request.path_info }}?t=delete&aid={{ article.nid }}">删除</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="article-pagination">
        {{ pagination }}
    </div>
{% endblock %}

myblog-0.1.1/templates/backend_article_add.html
{% extends "backend_layout.html" %}

{% block css %}
    {% load static %}
    <script src="{% static 'plugins/kindeditor/kindeditor-all.js' %}"></script>
    <script src="{% static 'plugins/kindeditor/lang/zh-CN.js' %}"></script>
    <link rel="stylesheet" href="{% static 'plugins/kindeditor/themes/default/default.css' %}">
{% endblock %}


{# 这是使用form组件自动生成html元素 #}
{% block content %}
    <div class="article-info">
        <form action="{% url 'app-backend:backend-article' %}" method="post" novalidate onsubmit="return false">
            <input type="hidden" name="t" value="add">
            {% csrf_token %}
            {{ afm.as_ul }}
            <button class="jsSubmit btn btn-success">发布</button>
        </form>
    </div>
{% endblock %}


{% block js %}
    <script src="{% static 'js/initkindeditor.js' %}"></script>
{% endblock %}

myblog-0.1.1/templates/backend_article_edit.html
{% extends "backend_layout.html" %}

{% block css %}
    {% load static %}
    <script src="{% static 'plugins/kindeditor/kindeditor-all.js' %}"></script>
    <script src="{% static 'plugins/kindeditor/lang/zh-CN.js' %}"></script>
    <link rel="stylesheet" href="{% static 'plugins/kindeditor/themes/default/default.css' %}">
{% endblock %}


{# 这是使用form组件自动生成html元素 #}
{% block content %}
    <div class="article-info">
        <form action="{% url 'app-backend:backend-article' %}" method="post" novalidate onsubmit="return false">
            <input type="hidden" name="aid" value="{{ aid }}">
            <input type="hidden" name="t" value="edit">
            {% csrf_token %}
            {{ afm.as_ul }}
            <button class="jsSubmit btn btn-success">发布</button>
        </form>
    </div>
{% endblock %}


{% block js %}
    <script src="{% static 'js/initkindeditor.js' %}"></script>
{% endblock %}

myblog-0.1.1/templates/backend_develop.html
{% extends 'backend_layout.html' %}

{% block content %}
    <h1>该模块还在开发中，敬请期待！</h1>
{% endblock %}

myblog-0.1.1/templates/backend_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% load static %}
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'js/menu_option_click.js' %}"></script>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/backend/backend_index.css' %}">
    {% block css %}{% endblock %}
</head>
<body>
<div class="head-area">
    <div class="logo left">LuckySonia</div>
    <div class="nav-list left">
        <div class="nav-item">
            <a class="nav-item-title" href="{% url 'user-web:index' %}">首页</a>
        </div>
        <div class="nav-item">
            <a class="nav-item-title" href="{% url 'user-web:home_article_list'  request.logged_blog.site %}">个人主页</a>
        </div>
    </div>
    <div class="nav-list right">
        <div class="nav-item author-avatar">
            <a class="nav-item-title" href="#">
                <img src="{% static 'img/avatar/default.png' %}" alt="">
                <span>{{ request.logged_blog.user.name }}</span>
            </a>
        </div>
        <div class="nav-item"><a class="nav-item-title" href="{% url 'app-backend:backend-logout' %}">退出登录</a></div>
    </div>
</div>

<div class="body-area">
    <div class="menu-area">
        {{ request.user_menu }}
    </div>
    <div class="content-area">
        {% block content %}{% endblock %}
    </div>
</div>

{% block js %}{% endblock %}
</body>
</html>

myblog-0.1.1/templates/backend_tag.html
{% extends 'backend_layout.html' %}

{% block css %}
    {% load static %}
    <script src="{% static 'js/ajaxAction.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>
    <script>
        $(function(){
            ajaxFormSubmitEvent('.item-fm', "button");
            ajaxModalEditEvent('.item-table .option-edit', '.myModal', '.modal-body .error-tip');
            ajaxDeleteEvent('.item-table .option-delete')
        })
    </script>
{% endblock %}

{% block content %}
    <div class="content-item-area item-add">
        <div class="item-title">添加文章标签</div>
        <form class="item-fm" action="{% url 'app-backend:backend-tag' %}" method="post" novalidate onsubmit="return false">
            <input type="hidden" name="t" value="add">
            {% csrf_token %}
            <li>
                <label for="id_title">标签名称(32个字符以内)</label>
                <span class="error-tip"></span>
                <input id='id_title' class="form-control" type="text" name="title" maxlength="32" required>
            </li>
            <li>
                <button class="btn btn-success">添加标签</button>
            </li>
        </form>
    </div>
    <div class="content-item-area item-list">
        <div class="item-title">文章标签列表</div>
        <table class="item-table table table-hover">
            <thead>
            <tr>
                <th class="article-title">标题</th>
                <th>文章数量</th>
                <th class="article-ope">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for tag in tag_lst %}
                <tr nid="{{ tag.nid }}">
                    <td class="option-title"><a href="/{{ request.logged_blog.site }}/tag/{{ tag.nid }}.html">
                        {{ tag.title }}
                    </a></td>
                    <td>{{ tag.article_count }}</td>
                    <td>
                        {% if 'edit' in request.user_action %}
                            <a class="option-edit" href="{% url 'app-backend:backend-tag' %}?t=edit&nid={{ tag.nid }}">编辑</a>
                        {% endif %}
                        {% if 'delete' in request.user_action %}
                            <a class="option-delete" href="{% url 'app-backend:backend-tag' %}?t=delete&nid={{ tag.nid }}">删除</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="myModal modal fade" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="gridSystemModalLabel">标签名编辑</h4>
                    </div>
                    <div class="modal-body">
                        <form action="{% url 'app-backend:backend-tag' %}" method="post" novalidate onsubmit="return false">
                            {% csrf_token %}
                            <input type="hidden" name="t" value="edit">
                            <input class="modal-option-nid" type="hidden" name="nid" value="">
                            <li>
                                <label for="id_title">标签名(32个字符以内)</label>
                                <span class="error-tip"></span>
                                <input class="modal-option-title form-control" id='id_title' type="text" name="title" maxlength="32" required>
                            </li>
                            <button type="button" class="ajaxModalSubmit btn btn-primary">保存更改</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="article-pagination">
        {{ pagination }}
    </div>
{% endblock %}

myblog-0.1.1/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/ajaxLogout.js' %}"></script>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
<div class="head-area">
    <div class="head-outer layout-outer">
        <div class="head-inner layout-inner">
            <a class="web-logo left" href="{% url 'user-web:index' %}">
                    LuckySonia
            </a>
            <div class="nav-left left">
            </div>
            <div class="nav-right right">
                {% if request.payload.logged_in_blog %}
                    <div class="nav-item account-area">
                        <a class="logged-account" href="{% url 'user-web:home_article_list' request.payload.logged_in_blog.site %}">
                            <i class="fa fa-user-circle fa-2x user-icon" aria-hidden="true"></i>
                            <span>
                                {% if request.payload.logged_in_blog.user.nickname %}
                                    {{ request.payload.logged_in_blog.user.nickname }}
                                {% else %}
                                    {{ request.payload.logged_in_blog.user.name }}
                                {% endif %}
                            </span>
                        </a>
                        <div class="nav-item-content">
                            <a href="{% url 'user-web:home_article_list' request.payload.logged_in_blog.site %}">主页</a>
                            <a href="{% url 'app-backend:backend-index' %}">管理</a>
                            <a class="account-logout" href="javascript:void(0)" url="{% url 'user-web:logout' %}">退出登录</a>
                        </div>
                    </div>
                {% else %}
                    <div class="nav-item">
                        <a href="{% url 'user-web:login' %}">登录</a>
                    </div>
                    <div class="nav-item">
                        <a href="{% url 'user-web:reg' %}">注册</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="body-area">
    <div class="body-outer layout-outer">
        <div class="body-inner layout-inner">
            <div class="menu-area menu-left">
                <div class="webplate menu-item">
                    <div class="webplate-title menu-item-title">网站板块</div>
                    <div class="webplate-option menu-item-option">
                        <ul>
                            {% for plate in plate_lst %}
                                {% if plate.nid == plate_id %}
                                    <li><a class="active" href="{% url 'user-web:index' %}?plate={{ plate.nid }}">{{ plate.title }}({{ plate.article_count }})</a></li>
                                {% else %}
                                    <li><a href="{% url 'user-web:index' %}?plate={{ plate.nid }}">{{ plate.title }}({{ plate.article_count }})</a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="content-area">
                <div class="article-list">
                    {% for article in article_lst %}
                        <div class="article-list-item">
                            <div class="article-title">
                                <a href="/{{ article.blog.site }}/{{ article.nid }}.html">{{ article.title }}</a>
                            </div>
                            <div class="article-summary">
                                <div class="author-avatar">
                                    <a href="{{ article.blog.site }}.html">
                                        <img src="{% static 'img/avatar/default.png' %}" alt="">
                                    </a>
                                </div>
                                <a href="/{{ article.blog.site }}/{{ article.nid }}.html">{{ article.summary }}</a>
                            </div>
                            <div class="article-foot">
                                <a class="author-index" href="{{ article.blog.site }}.html">
                                    {% if article.blog.user.nickname %}
                                        {{ article.blog.user.nickname }}
                                    {% else %}
                                        {{ article.blog.user.name }}
                                    {% endif %}
                                </a>发布于
                                <span>{{ article.create_time|date:"Y-m-d H:i:s" }}</span>
                                <span>阅读({{ article.read_count }})</span>
                                <span>赞({{ article.up_count }})</span>
                                <span>踩({{ article.down_count }})</span>
                                <a href="#">评论</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="article-pagination">
                    {{ pagination }}
                </div>
            </div>
            <div class="menu-area menu-right">
                <div style="width: 100%;height:800px">
                    排行榜或者广告区
                </div>
            </div>
        </div>
    </div>
</div>
<div class="foot-area"></div>
</body>
</html>

myblog-0.1.1/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/account.js' %}"></script>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
</head>
<body>
<div class="account-outer">
    <div class="account-inner">
        <div class="account-title">
            用户登录
        </div>
        <div class="account-err-tip">
            <span></span>
        </div>
        <form class='account-fm form-horizontal' action="{% url 'user-web:login' %}" method="post" novalidate onsubmit="return false">
            {% csrf_token %}
            <div class="fm-item form-group">
                <label class="col-sm-3" for="id_user">用户名</label>
                <div class="col-sm-9">
                    <input type="text" name="user" id="id_user" class="regValidate form-control" placeholder="用户名">
                    <span class="jsTipUser"></span>
                </div>
            </div>

            <div class="fm-item form-group">
                <label class="col-sm-3" for="id_pwd">密码</label>
                <div class="col-sm-9">
                    <input type="password" name="pwd" id="id_pwd" class="regValidate form-control" placeholder="密码">
                    <span class="jsTipPwd"></span>
                </div>
            </div>

            <div class="fm-item form-group">
                <label class="col-sm-3" for="id_check_code">验证码</label>
                <div class="col-sm-9">
                    <div class="col-sm-4">
                        <input type="text" name="check_code"  id="id_check_code" class="check_code form-control" placeholder="验证码" >
                    </div>
                    <div class="col-sm-offset-1 col-sm-7">
                        <img class="jsCodeImg" src="{% url "user-web:check_code" %}" alt="">
                    </div>
                    <span class="jsTipCode"></span>
                </div>
            </div>
            <button class="jsSubmit btn btn-success">登录</button>
        </form>
        <div class="account-foot">
            <span>没有账户？<a href="{% url 'user-web:reg' %}">立即注册</a></span>
        </div>
    </div>
</div>
<script>
    $(function() {
        let obj = new AccountValidate([".regValidate", ".check_code"]);
        obj.EventBind();
        obj.submitEvent();
    });
</script>
</body>
</html>

myblog-0.1.1/templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/account.js' %}"></script>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
</head>
<body>
<div style="width: 400px; margin: 20px auto; text-align: center; font-size: 30px; line-height: 30px; height: 30px; color: red">
    暂不对外开放注册
</div>
<div class="account-outer">
   <div class="account-inner">
        <div class="account-title">
            用户注册
        </div>
        <form class='account-fm form-horizontal' action="{% url 'user-web:reg' %}" method="post" novalidate onsubmit="return false">
            {% csrf_token %}
            <div class="fm-item form-group">
                <label class="col-sm-3" for="id_user">用户名</label>
                <div class="col-sm-9">
                    <input type="text" name="user" id="id_user" class="regValidate form-control" placeholder="用户名">
                    <span class="jsTipUser"></span>
                </div>
            </div>
            <div class="fm-item form-group">
                <label class="col-sm-3" for="id_email">邮箱</label>
                <div class="col-sm-9">
                    <input type="email" name="email" id="id_email" class="regValidate form-control" placeholder="邮箱">
                    <span class="jsTipEmail"></span>
                </div>
            </div>
            <div class="fm-item form-group">
                <label class="col-sm-3" for="id_pwd">密码</label>
                <div class="col-sm-9">
                    <input type="password" name="pwd" id="id_pwd" class="regValidate form-control" placeholder="密码">
                    <span class="jsTipPwd"></span>
                </div>
            </div>
            <div class="fm-item form-group">
                <label class="col-sm-3" for="id_confirm_pwd">确认密码</label>
                <div class="col-sm-9">
                    <input type="password" name="confirm_pwd" id="id_confirm_pwd" class="confirm_pwd form-control" placeholder="确认密码">
                    <span class="jsTipConfirm"></span>
                </div>
            </div>
            <div class="fm-item form-group">
                <label class="col-sm-3" for="id_check_code">验证码</label>
                <div class="col-sm-9">
                    <div class="col-sm-4">
                        <input type="text" name="check_code"  id="id_check_code" class="check_code form-control" placeholder="验证码" >
                    </div>
                    <div class="col-sm-offset-1 col-sm-7">
                        <img class="jsCodeImg" src="{% url "user-web:check_code" %}" alt="">
                    </div>
                    <span class="jsTipCode"></span>
                </div>
            </div>
            <button class="jsSubmit btn btn-success">注册</button>
        </form>
       <div class="account-foot">
           <span>已有账户？<a href="{% url 'user-web:login' %}">立即登录</a></span>
       </div>
    </div>
</div>
<script>
$(function() {
    let obj = new AccountValidate([".regValidate", ".confirm_pwd", ".check_code"]);
    obj.EventBind();
    obj.submitEvent();
});
</script>
</body>
</html>

myblog-0.1.1/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .menu-item-content {
            margin-left: 20px;
            display: none
        }
        .menu-item-content>a {
            display: block;
        }
        .menu-item-content.active {
            display: block;
        }
    </style>
</head>
<body>
    {{ safestring }}
</body>
</html>